name: Windows

release:
  types: [published]

jobs:
  runner-test:
    runs-on: ubuntu-18.04
    env:
      BETA_RELEASE: ${{ github.event.release.prerelease }}
    steps:
      - uses: actions/checkout@v2
      - run: echo $BETA_RELEASE
