name: Windows

on: push

jobs:
  runner-test:
    runs-on: windows-2019
    env:
      CHOCO_CACHE: ${{ github.workspace }}\.cache\
      OPENSSL_VERSION: 1.1.1.900
      OPENSSL_LIGHT_VERSION: 1_1_1i
      OPENSSL_LIGHT_DIR: ${{ env.CHOCO_CACHE }}\openssl-light-dl\
    steps:
      - name: Output
        run: Get-ChildItem $([System.IO.Path]::GetDirectoryName($(Get-Command openssl | Select-Object -ExpandProperty Source)))

      - name: Cache chocolatey
        id: cache-choco
        uses: actions/cache@v1
        with:
          path: ${{ env.CHOCO_CACHE }}
          key: ${{ runner.os }}-Choco_${{ env.OPENSSL_VERSION }}-${{ env.OPENSSL_LIGHT_VERSION }}

      - name: Install OpenSSL (full)
        run: choco install openssl --version ${{ env.OPENSSL_VERSION }} -c ${{ env.CHOCO_CACHE }} --no-progress
      
      - name: Download OpenSSL Light (32bit)
        uses: suisei-cn/actions-download-file@v1
        id: openssl-light-msi
        with:
          url: "https://slproweb.com/download/Win32OpenSSL_Light-${{ env.OPENSSL_LIGHT_VERSION }}.msi"
          target: ${{ env.OPENSSL_LIGHT_DIR }}

      - name: Setup OpenSSL Light (32bit)
        run: msiexec /a ${{ env.OPENSSL_LIGHT_DIR }}${{ steps.openssl-light-msi.outputs.filename }} TARGETDIR=${{ github.workspace }}\ext\openssl\

      - name: Output
        run: Get-ChildItem -Recurse ${{ github.workspace }}\ext\
