name: Windows

on: push

jobs:
  runner-test:
    runs-on: windows-2019
    steps:
      - name: Find existing openssl.light
        run: Write-Output $(Get-Command openssl | Select-Object -ExpandProperty Definition)
      
      - name: Install OpenSSL (full)
        run: choco install openssl
      
      - name: New OpenSSL
        run: Write-Output $(Get-Command openssl | Select-Object -ExpandProperty Definition)
