name: Windows

on: push

jobs:
  runner-test:
    runs-on: windows-2019
    steps:
      - name: Find existing openssl.light
        run: Write-Output $(Get-Command openssl | Select-Object -ExpandProperty Definition)